### ISSUE TITLE
Png export

### ISSUE THREAD

**Issue by procfxgen** [jaime-olivares/vscode-yuml#11]
Add png image support.

**Comment by jaime-olivares** [comment]
Still looking at this. Cannot find a clean way to do it. 
The VSCode extension API doesn't provide access to the DOM, so it cannot be done by using DOM objects.
Don't really want to use a dependency like _PhantomJS_ or _ImageMagick_, as there is no certainty to work well in all installations.

**Comment by jaime-olivares** [comment]
This won't happen anytime soon. there are lots of technical barriers for doing this smoothly in pure javascript. I am reluctant of using any kind of 3rd party binary as it will trigger a lot of installation issues in multiple platforms.
