### ISSUE TITLE
Opening multiple files

### ISSUE THREAD

**Issue by mbp** [jaime-olivares/vscode-yuml#12]
Thanks for great tool!

When I open multiple yuml files and have the preview window open, it will switch back and forth them very quickly multiple times.

**Comment by jaime-olivares** [comment]
Please specify your platform (Windows/macOS/Linux) and VSCode version.

**Comment by jaime-olivares** [comment]
I am trying with Code 1.6 and macOS, with 3 and 4 yuml files at opened and it doesn't happen.
The 4 files opened in the left pane, and the preview shown in the right pane.

**Comment by mbp** [comment]
1.6, Windows 10.

**Comment by jaime-olivares** [comment]
@mbp Please update to VS Code 1.6.1 and let me know if the issue persists

**Comment by mbp** [comment]
It's the same

**Comment by corretge** [comment]
Works fine with
vsCode 1.10.2 
yUML 2.10.0
OS/X 10.12.3

Great tool!

**Comment by jaime-olivares** [comment]
Closing as no more reports received
