### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by mbp** [jaime-olivares/vscode-yuml#13]
I am often experiencing problems with the window not responding when opening a yuml file.

But it's not every time, and just when I was about to type this issue, the problem went away, only to appear a few minutes later.

So sorry, not much to go for. Not sure how I can help debug this issue?

**Comment by jaime-olivares** [comment]
>>I am often experiencing problems with the window not responding when opening a yuml file.

Which window?

**Comment by jaime-olivares** [comment]
Please specify your platform (Windows/macOS/Linux) and VSCode version.

**Comment by mbp** [comment]
The window of the entire application.

![image](https://cloud.githubusercontent.com/assets/77322/19300726/2062987e-905c-11e6-86bf-f71cc5d8e82e.png)


1.6, Windows 10.

**Comment by jaime-olivares** [comment]
@mbp Please update to VS Code 1.6.1 and let me know if the issue persists

**Comment by mbp** [comment]
It's the same

**Comment by jaime-olivares** [comment]
Sorry, still couldn't reproduce the issue with a couple of Windows machines
