### ISSUE TITLE
error when showing diagram

### ISSUE THREAD

**Issue by jimmymain** [jaime-olivares/vscode-yuml#14]
```
Class         [Customer]
```

No handler found for the command: 'extension.viewYumlDiagram'. An extension might be missing an activation event.

**Comment by jaime-olivares** [comment]
Hi Jim, I see you have closed this bug. Is it solved?
Otherwise, could you please attach the yuml file you are trying as well as information about your environment? (OS and VSCode version)

**Comment by jimmymain** [comment]
I reinstalled code - I think it was a config / install issue that solved
itself after the reinstall
