### ISSUE TITLE
Better handling of the '[' and ']' characters in the body of the object

### ISSUE THREAD

**Issue by ttrider** [jaime-olivares/vscode-yuml#15]
Ideally, I would like to prepend '[' and ']' with a backslash, so I can these characters in property names and notes.

Something like '[This is a note about item \[123\] in array]

Thanks,

Vladimir

**Comment by jaime-olivares** [comment]
hi Vladimir, I think that's the case, but I will review it, something like this shall work:

````[This is a note about item \\[123\\] in array]````

**Comment by ttrider** [comment]
Unfortunately, neither \\[ nor \[ worksL

 

 

 

I looked at the code and I think that the splitYumlExpr function needs to be improved to support this scenario.

 

I was playing with idea of the ‘universal’ regex to split the string into parts, but I couldn’t build one because of the vanilla Javascript implementation of the regex (I needed a positive lookbehind feature).

 

The easiest way to solve it, but not an elegant one, I’m afraid, is to replace special characters prepended with ‘\’ before parsing and restore them after.

 

Kind of like this: 

 

this.splitYumlExpr = function(line, separators) {

        var word = "";

        var lastChar = null;

        var parts = [];

 

        // a special handling for the \( \) \< \> \| \[ \]

        // we are going to replace them with special characters and restore after

        // the parsing

        line = line

            .replace(/\\\(/g, '&&op&&')

            .replace(/\\\)/g, '&&cp&&')

            .replace(/\\\[/g, '&&osp&&')

            .replace(/\\\]/g, '&&csp&&')

            .replace(/\\\</g, '&&oap&&')

            .replace(/\\\>/g, '&&cap&&')

            .replace(/\\\|/g, '&&pp&&');

 

        for (var i = 0; i < line.length; i++) {

            c = line[i];

 

            if (separators.indexOf(c) >= 0 && lastChar === null) {

                if (word.length > 0) {

                    parts.push(word.trim());

                    word = "";

                }

 

                switch (c) {

                    case '[':

                        lastChar = ']';

                        break;

                    case '(':

                        lastChar = ')';

                        break;

                    case '<':

                        lastChar = '>';

                        break;

                    case '|':

                        lastChar = '|';

                        break;

                    default:

                        lastChar = null;

                        break;

                }

                word = c;

            } else if (c === lastChar) {

                lastChar = null;

                parts.push(word.trim() + c);

                word = "";

            } else {

                word += c;

            }

        }

 

        if (word.length > 0)

            parts.push(word.trim());

 

        // replace back

        for (var p = 0; p < parts.length; p++) {

 

            parts[p] = parts[p]

                .replace(/&&op&&/g, '(')

                .replace(/&&cp&&/g, ')')

                .replace(/&&osp&&/g, '[')

                .replace(/&&csp&&/g, ']')

                .replace(/&&oap&&/g, '<')

                .replace(/&&cap&&/g, '>')

                .replace(/&&pp&&/g, '|');

        }

 

 

        return parts;

    }

 

As I said, not an elegant, but workable solution….

 

Thank You,

 

Vladimir

**Comment by chezwicker** [comment]
Created https://github.com/jaime-olivares/vscode-yuml/pull/18 with another idea for a fix. Please have a look.

Not sure how to link the PR to this issue, thought it might be about the title - unfortunately not... Please advise.

**Comment by chezwicker** [comment]
Replaced the PR by an improved https://github.com/jaime-olivares/vscode-yuml/pull/19. Sorry, have to edit from a web terminal...

**Comment by jaime-olivares** [comment]
Already solved in PR #19
