### ISSUE TITLE
Problem with Notes

### ISSUE THREAD

**Issue by chezwicker** [jaime-olivares/vscode-yuml#23]
There seems to be a problem with the 2.10.0 package, diagrams with notes aren't displayed correctly. Could this be related to the viz.js 1.7.1 upgrade? In my workspace, using 1.3.0, everything works fine.

**Comment by jaime-olivares** [comment]
I tried the ready-made examples. Could you please post the difference?

**Comment by chezwicker** [comment]
As an example, here are the first lines from the class diagram (that works)
```
// {type:class}
// {direction:topDown}
[note: You can stick notes on diagrams too!{bg:cornsilk}]
[Customer]<>1-orders 0..*>[Order]
```
Unfortunately, adding one more line with a note does not:
```
// {type:class}
// {direction:topDown}
[note: You can stick notes on diagrams too!{bg:cornsilk}]
[Customer]<>1-orders 0..*>[Order]
[Order]-[note:asdf]
```

For comparison (to be sure about the syntax): http://yuml.me/edit/184be5b8

This is running on VSC 1.9.1 with vscode-yuml 2.10.0. To be sure, I tried the same workspace with 1.3.0 and 1.7.1. Runs perfectly with 1.3.0, but not with 1.7.1.

**Comment by chezwicker** [comment]
Any update on this? Were you able to reproduce the problem? The easiest option might be to revert to 1.3.0 for now...

**Comment by jornj** [comment]
I've just experienced problems with notes in class diagrams for VSC 1.18.1. Extension yUML version 2.10.0.

The note field works just fine alone, but causes an error when attached to a class, as seen with the example from the vscode-yuml wiki: 
`[Address]-[note: Value Object]` results in `Error composing the diagram`

**Comment by jaime-olivares** [comment]
This issue has been isolated and determined that is caused by newer versions of viz.js

I will use an old version of viz-lite.js
