### ISSUE TITLE
Sequence diagram enhancement 

### ISSUE THREAD

**Issue by corretge** [jaime-olivares/vscode-yuml#24]
Thanks for your tootl, it's very useful!

Just to know your plans to add sequence diagram like https://github.com/bramp/js-sequence-diagrams 

I read that it's in your roadmap. I never wrote a vsCode extension, but If I can help, tell me.

**Comment by jaime-olivares** [comment]
Hi, I will resume the development of this extension very soon, and will start with the mentioned sequence diagram.

**Comment by jaime-olivares** [comment]
I have already commenced. Will have a new release in very few days.

**Comment by jaime-olivares** [comment]
It is published now, with basic functionalities.
