### ISSUE TITLE
No syntax highlighting

### ISSUE THREAD

**Issue by AttilaGal** [jaime-olivares/vscode-yuml#25]
yuml files seem to register as plain text files by vsc (and no .yuml file extension available when trying to change it manually)

running on mac os sierra 10.12.1
vscode: 1.12.2
vscode-yuml: 2.10.0 

screenshot for example:
![image](https://cloud.githubusercontent.com/assets/6709071/26728124/6d936100-47a9-11e7-82f3-1d53439fbdaf.png)

**Comment by jaime-olivares** [comment]
I have tried last versions of VSCode in Windows and macOS. Please verify that your issue is not related to another theme extension.

**Comment by AttilaGal** [comment]
Thank you for the quick response! 
It seems that other theme extensions such as Sublime Material Theme or Darcula extension interferes with the syntax highlighting, is there a way to have both?

**Comment by jaime-olivares** [comment]
Hi, as this extension was working well so far, the conflict is in the other extension and the resolution shall be done there.
