### ISSUE TITLE
new features for copying from preview and background setting

### ISSUE THREAD

**Issue by deansay** [jaime-olivares/vscode-yuml#26]
**User Case 1**: Document integreted with yuml.
We want to copy yuml as <png> image from preview or export as a command.

**User Case 2**: Background color setting.
White for background color,and draw as black or other color.

**Comment by jaime-olivares** [comment]
Hi there,
Case 1 has been discarded long time ago due to technical limitations.
Case 2 - I will consider it. Currently it senses if the editor is configured in light or dark theme.

**Comment by jaime-olivares** [comment]
Not a priority for now.
