### ISSUE TITLE
Export a diagram to PDF

### ISSUE THREAD

**Issue by paillave** [jaime-olivares/vscode-yuml#27]
An export to PDF would be a fantastic feature.

**Comment by jaime-olivares** [comment]
I don't think this can be achieved with a pure nodejs module. It should require some binary, which is highly undesirable. Probably using an online service...

**Comment by paillave** [comment]
I understand your concert and you are right. Nevertheless it seems to be possible to make a pdf out of an svg with a pure js library like https://github.com/CBiX/svgToPdf.js/.

**Comment by colin-young** [comment]
I'd be happy just to export the SVG (or, better, auto-generate an SVG file) which I could include in my git repo and reference in markdown for documentation.

**Comment by jaime-olivares** [comment]
Comments regarding the yUML syntax should be done now in https://github.com/jaime-olivares/yuml-diagram

**Comment by jaime-olivares** [comment]
Please read: https://github.com/jaime-olivares/vscode-yuml/issues/49
