### ISSUE TITLE
Chinese support before, now does not support Chinese?

### ISSUE THREAD

**Issue by yinbaoqiang** [jaime-olivares/vscode-yuml#28]
Chinese is no longer supported after the automatic upgrade plug-in, but also plans to support Chinese?

**Comment by jaime-olivares** [comment]
I will support chinese again whenever I find a version that doesn't trigger issue #23 

Help is welcome.

**Comment by zhfjyq** [comment]
using viz.js ver 1.8.1 can support chinese, and not trigger #23

**Comment by jaime-olivares** [comment]
Hi, thanks for reviewing. I will look at it and release as soon as possible.

**Comment by jaime-olivares** [comment]
using 1.8.1 now. Please confirm if Chinese is showing correctly.

**Comment by derekhu** [comment]
Thank you for this awesome UML tool.  It does support show Chinese, however , auto-line-break doesn't work as English words do in ```[note: something very long in Chinese]``` , eg: ```[note: 这是一段非常非常长的文本，但是不能很好的自动换行。]```
