### ISSUE TITLE
Add <<extend>> and <<include>> stereotype labels for (a)<(b) and (a)>(b) in use case diagrams

### ISSUE THREAD

**Issue by ProfessorO** [jaime-olivares/vscode-yuml#31]
I see the code to add the appropriate edge labels in scripts/usecase-diagram.js, but they're not showing up for me at all. I know viz.js can do labels (at least the latest version can), so I'm not sure why they don't show up.

**Comment by ProfessorO** [comment]
Found the solution literally a few seconds after submitting the issue. It's line 129 in scripts/usecase-diagram.js, where element[1][2].len should be .len**gth** instead. I'll submit a PR when I get a minute.

**Comment by jaime-olivares** [comment]
Thanks, this will be included in the next release in few days
