### ISSUE TITLE
Font is pretty big in markdown and doesn't always fit nicely

### ISSUE THREAD

**Issue by DeStilleGast** [jaime-olivares/vscode-yuml#33]
This is pure a example, but in my opinion this is a big font, could there be a option to define a font or font size ??

![afbeelding](https://user-images.githubusercontent.com/3677706/37021267-47d4f910-211f-11e8-871d-3d4e306b29c0.png)

Note: I'm not sure if this only occurse in markdown

**Comment by jaime-olivares** [comment]
Hi there, I will investigate that.

**Comment by jaime-olivares** [comment]
@DeStilleGast 
I have tried in macOS and Windows 10 an it is not happening. Please describe your platform.

**Comment by DeStilleGast** [comment]
Microsoft Windows 10 Enterprise
10.0.16299 N/A Build 16299
vscode version 1.21.1

**Comment by DeStilleGast** [comment]
I noticed when I updated visual studio code, it got fixed.
