### ISSUE TITLE
Nesting classes into packages or simple bounding boxes

### ISSUE THREAD

**Issue by SvenHubert** [jaime-olivares/vscode-yuml#34]
In order to use the class diagram in more complex projects (> 10 classes), we need to have some kind of boundary around some classes - e.g. bounded context for DDD-like approaches or packages referring to UML. 

In a first step, a simple bounding box (e.g. dotted rectangle in grey) with some label (top, center) would be sufficient.

The definition could look like the package diagram, plus based on indented classes and namespaces:
```
[Context1]
   [MyClass]
   ...
[Context2]
   [MyOtherClass]
   [MyOtherClass]->[Context1.MyClass]
   [MyClass]-[note: this is a different class than MyClass from Context1 with different relations.]
```

Regards

Sven

**Comment by SvenHubert** [comment]
For an idea of how to introduce different boundary or package styles, please refer to: [PlantUml Package Style Types](http://plantuml.com/class-diagram#PStyle).

This could be defined like the color:
`[Context1{style:cloud}]`

**Comment by jaime-olivares** [comment]
Hi Sven,
I will consider it.
The indentation doesn't seem to be the "yUML way", though.

**Comment by jaime-olivares** [comment]
Comments regarding the yUML syntax should be done now in https://github.com/jaime-olivares/yuml-diagram
