### ISSUE TITLE
Auto-magically convert C# classes into yUML?

### ISSUE THREAD

**Issue by BryanWilhite** [jaime-olivares/vscode-yuml#35]
I wrote [a little LINQPad sample](https://github.com/BryanWilhite/LinqPad/blob/master/Queries/funkyKB/System.Reflection%20-%20converting%20Field%2C%20Method%20and%20PropertyInfo%20to%20yUML.linq) to convert a class into yUML:

![clipboard02](https://user-images.githubusercontent.com/5226627/37187745-84055fd2-2300-11e8-86e9-6e1ebd6f580c.png)

Is there a roadmap toward adding this bit functionality?

![clipboard01](https://user-images.githubusercontent.com/5226627/37187725-653fa92c-2300-11e8-8311-d3a665a901bd.png)

**Comment by jaime-olivares** [comment]
Hi Bryan, 
This is a great application of yUML diagrams!
However, I think it shouldn't be part of the yUML extension, but a separate extension. Consider there are lots of programming languages out there, and they would have the same requirement.
I would love to see it materialized.
