### ISSUE TITLE
Issue with markdown support

### ISSUE THREAD

**Issue by dragonforce2010** [jaime-olivares/vscode-yuml#36]
I try to use the below syntax to render it in the browser, but it's not working.
```
```yuml
{type: sequence}
[A]>[B]
```
How can I properly render the yuml in the browser? I want to add some class/activity diagrams in my readme.md and push it to github.

Thanks.

**Comment by jaime-olivares** [comment]
Hi, you are missing the // before the type, also missing the trailing tick marks:

    ```yuml
    // {type: sequence}
    [A]>[B]
    ```

I assume all this is happening inside a markdown document (.md)
