### ISSUE TITLE
Brackets in class diagrams preview

### ISSUE THREAD

**Issue by vcappello** [jaime-olivares/vscode-yuml#43]
There seems to be a problem with in class diagrams preview, the class name was displayed enclosed by braces. 
When the class was defined including attributes the  braces open before the class name and close after last attribute.

<img width="558" alt="vscode-yuml-issue" src="https://user-images.githubusercontent.com/1203028/41093461-ac00700c-6a4b-11e8-961e-801882cf483f.PNG">

**Comment by jaime-olivares** [comment]
Closed, as moved to the proper github project.
