### ISSUE TITLE
Positionings with drag and drop

### ISSUE THREAD

**Issue by FrediLehmann** [jaime-olivares/vscode-yuml#44]
Hi,

It would be nice to have more flexibility of positionings.
I thougt something with drag and drop would be cool.

I don't know if that is even possible.

Would love to contribute for that.

**Comment by FailRapids** [comment]
Hey there you can have it generate an svg file then you can edit how you like but the ability to do that from the editor would be nice

**Comment by jaime-olivares** [comment]
This is not possible.  The graphviz library doesn't have that capability.

Relying on the svg won't work either, as it would have to re-route some connecting lines, which is done by the graphviz library.
