### ISSUE TITLE
Suggestion for auto-generating .yuml files

### ISSUE THREAD

**Issue by greg-murray-volusion** [jaime-olivares/vscode-yuml#45]
It would be cool to combine with this project:

https://github.com/remojansen/TsUML

That way we could generate the `.yuml` file from scanning the typescript files from the project.

The [code already has a getDsl function](https://github.com/remojansen/TsUML/blob/44694fe847cedd8038f6b6718a1641aa0ed1c80e/src/core/index.ts#L47), so just needs to be integrated.

It does have some different syntax than this project.  Here's a sample string it generates.

    [Weapon{bg:palegreen}][Weapon||tryHit();],[Named{bg:palegreen}][Named|name;|],[BaseWeapon{bg:skyblue}][BaseWeapon|damage;|],[Katana{bg:skyblue}][Katana|name;|tryHit();],,[BaseWeapon]^-[Katana],[Weapon]^-[Katana],[Named]^-[Katana],[Ninja{bg:skyblue}][Ninja|_weapon;|fight();],

The commas would need to be converted to new lines and it does some stuff with pipes and semi-colons that is not compatible.

**Comment by jaime-olivares** [comment]
Hi Greg,
I have received this suggestion before. My answer is the same: I cannot specialize this extension for a single programming language. I suggest to create a different extension that creates the yuml files based on the specific programming language.

**Comment by greg-murray-volusion** [comment]
ok, thanks Jaime.
