### ISSUE TITLE
No syntax highlighting in Markdown

### ISSUE THREAD

**Issue by garkin** [jaime-olivares/vscode-yuml#47]
I have a single extension, `yUML 3.1.2`.

![image](https://user-images.githubusercontent.com/422774/46582932-def0a800-ca78-11e8-8a33-aa11edaec34a.png)

**Comment by garkin** [comment]
PlantUML has it implemented: 
https://github.com/qjebbs/vscode-plantuml/pull/95/files

**Comment by jaime-olivares** [comment]
Done. Will be deployed with version 3.3.0
