### ISSUE TITLE
Note annotation not rendered in sequence diagram

### ISSUE THREAD

**Issue by Narayane** [jaime-olivares/vscode-yuml#48]
Hi,

First, thanks for your work.

It seems note annotation is not currently rendering when I visualize a sequence diagram (_Error parsing the yUML file_). I use the yUML plugin v3.1.2 and VS Code v1.28.0.

**Comment by Narayane** [comment]
Consequence of this I guess: https://github.com/jaime-olivares/yuml-diagram/issues/9

**Comment by jaime-olivares** [comment]
The source issue has been fixed
