### ISSUE TITLE
Error when moving the diagram tab to display below the code

### ISSUE THREAD

**Issue by RCVarley** [jaime-olivares/vscode-yuml#53]
I got the below error when I tried to move the diagram tab to display below the code.  You have to restart vscode to get the extension to work again.

Unable to open '\vscode-yuml': ModelService: Cannot add model because it already exists!.

**Comment by jaime-olivares** [comment]
Does it still happen with VS Code 1.30.2 ?

**Comment by jaime-olivares** [comment]
Fixed in 3.2
