### ISSUE TITLE
Diagrams not shown

### ISSUE THREAD

**Issue by makorne** [jaime-olivares/vscode-yuml#56]
Just installed over VS extentions

But looks like its not working.
No text highlihted and no diagramms displayed

Please, provide any 100% working example.

**Comment by jaime-olivares** [comment]
This is a bit weird. I don't have any other report like the one.
Please describe your environment (OS, VSCode) and the samples you have used.

**Comment by nboukeffa** [comment]
Hi, same for me with this simple code: `[Customer]`. 
I'm running VSCode 1.31.1 on macOS 10.14.3.

Here what I see:
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/154042/53302049-730db100-385a-11e9-8535-befeff2c1083.png">

Thanks.

**Comment by jaime-olivares** [comment]
I have found the following behavior so far:
- If you try to open a yuml file, it will show the diagram without problems.
- If you create a new yuml file, it won't show the diagram (only that icon) **until you save it** 

Workaround: Save the file (Ctrl-S) to see the diagram

Please confirm if this is your case, while I finish to analyze and solve this.

**Comment by tvanriper** [comment]
I just installed vscode-yuml, and tried the same [Customer] thing but did not see a diagram show, even after saving it.

The image nboukeffa shows is exactly what I see.

I wish I could show you my environment to better help you... likely, the install didn't quite go correctly.

**Comment by jaime-olivares** [comment]
@nboukeffa (and possibly @tvanriper )
Your yuml code is not correct. It is lacking the diagram type:
````
// {type:class}
````

The preview shall show a warning message about it, but it isn't. I suspect it is a collateral of PR #57 

I will provide a new version in the following hours.

**Comment by jaime-olivares** [comment]
Fixed and published as version 3.4

**Comment by tvanriper** [comment]
That was indeed the issue.  It wasn't obvious to me (because I didn't read carefully enough) that you require the //{type:class} text.  If you browse to https://yuml.me and play around with their online editor, it doesn't have this requirement, which added to the confusion.

It makes sense to me, now that I see it... it just didn't immediately grab me.

For whatever it's worth, I think it is counter-intuitive that something classically appearing as a comment acts as a requirement.  That might have also made it harder for me to grab onto the concept.

**Comment by jaime-olivares** [comment]
There is some rationale behind it:

The yuml file shall contain the type, as we are not specifying the type in the URL as when you invoke yuml.me

As I didn't want to disturb too much the original specification, I used special comment. This is not an unusual practice, there are several language that have controlled comments.
