### ISSUE TITLE
Dark color theme for sequence diagram is wrong

### ISSUE THREAD

**Issue by Oblomoff** [jaime-olivares/vscode-yuml#59]
Hello!

![Annotation 2019-04-15 142608](https://user-images.githubusercontent.com/6727349/56129389-96b3c480-5f8a-11e9-98b3-4e450c8b11b8.png)

**Comment by jaime-olivares** [comment]
It seems something changed in the vscode API. I will check.

**Comment by jaime-olivares** [comment]
Updated the extension as version 3.5.0

**Comment by Oblomoff** [comment]
Thanks!
