### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ztomer** [jaime-olivares/vscode-yuml#70]
- Issue Type: `Performance`
- Extension Name: `yuml`
- Extension Version: `3.5.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.53.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ztome\AppData\Local\Temp\JaimeOlivares.yuml-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jaime-olivares** [comment]
I am not receiving such report with vscode 1.68

**Comment by ztomer** [comment]
Not reproduced on 1.70.2
