### ISSUE TITLE
Allow to save diagrams as an image

### ISSUE THREAD

**Issue by gMemiy** [jaime-olivares/vscode-yuml#72]
When you ready to share diagram with someone who have no this extention or vscode, you need to save the diagram somehow.

**Comment by aduh95** [comment]
Duplicate of https://github.com/jaime-olivares/vscode-yuml/issues/49?

TLDR is you need to add `// {generate:true}` in your YUML file.

**Comment by gMemiy** [comment]
Sorry. I didn't read other already closed requests with the same questions:
https://github.com/jaime-olivares/vscode-yuml/issues/49

{generate:true} option fully solved my question.
Thank you for convenient tool =)

**Comment by gMemiy** [comment]
> Duplicate of #49?

Yes, it is. Thank you!
My bad. I ask before reading others topics.
